#cloud-config
apt_update: true
package_upgrade: true

runcmd:
  - curl -O http://vestacp.com/pub/vst-install.sh
  - bash vst-install.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous no --mysql yes --postgresql no --hostname cl1.eduteka.pt --email joao.leitao@datasource.pt --password Vertigo1...

#!/bin/bash

apt-get update && apt-get upgrade -y
cd /root
curl -O http://vestacp.com/pub/vst-install.sh
bash vst-install.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous no --mysql yes --postgresql no --interactive no --hostname "cl1.eduteka.pt" --email "joao.leitao@datasource.pt" --password "Vertigo1..."

#cloud-config

# Update apt database on first boot
# (ie run apt-get update)
#
# Default: true
# Aliases: apt_update
package_update: false

# Upgrade the instance on first boot
# (ie run apt-get upgrade)
#
# Default: false
# Aliases: apt_upgrade
package_upgrade: true

timezone: "Lisbon/Europe"

# run commands
# default: none
# runcmd contains a list of either lists or a string
# each item will be executed in order at rc.local like level with
# output to the console
# - if the item is a list, the items will be properly executed as if
#   passed to execve(3) (with the first arg as the command).
# - if the item is a string, it will be simply written to the file and
#   will be interpreted by 'sh'
#
# Note, that the list has to be proper yaml, so you have to escape
# any characters yaml would eat (':' can be problematic)
runcmd:
 - [ ls, -l, / ]
 - [ sh, -xc, "echo $(date) ': hello world!'" ]
 - [ sh, -c, echo "=========hello world'=========" ]
 - ls -l /root
 - [ wget, "http://vestacp.com/pub/vst-install.sh", -O, /root/vst-install.sh ]
 - [ bash, /root/vst-install.sh, '--nginx yes', '--apache yes', '--phpfpm no', '--named yes', '--remi yes', '--vsftpd yes', '--proftpd no', '--iptables yes', '--fail2ban yes', '--quota no', '--exim yes', '--dovecot yes', '--spamassassin yes', '--clamav yes', '--softaculous no', '--mysql yes', '--postgresql no', '--interactive no', '--hostname "cl1.eduteka.pt"', '--email "joao.leitao@datasource.pt"', '--password "Vertigo1..."' ]
